language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
before_script:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm install codecov -g
  - codecov -f coverage/coverage-final.json
